#!/bin/bash
max=1024    # number of megabytes

mkdir generated
for ((i=1; i<=5; i++))
do
    echo Creating file
    dd bs=1M count=$(($RANDOM%max + 1)) if=/dev/urandom of=file$i
    md5sum file$i | awk '{print $1}' > before.txt
    mv file$i /home/felix/generated
    md5sum /home/felix/generated/file$i | awk '{print $1}' > after.txt
    diff before.txt after.txt > diff$i.txt
    rm before.txt
    rm after.txt
    if [ ! -s diff$i.txt ] ; then
        rm diff$i.txt
    fi
done
    rm -r generated/
    ls diff*
    echo "That is the list of corrupted files"
