#!/bin/bash
max=1024    # number of megabytes
if [ -d $1 ]; then
    echo "Directory $1 already exists"
else
mkdir $1
fi
for ((i=1; i<=$2; i++))
do
    echo Creating file$i
    dd bs=1M count=$(($RANDOM%max + 1)) if=/dev/urandom of=file$i
    a=$(md5sum file$i | awk '{print $1}')
    mv file$i $1
    b=$(md5sum $1/file$i | awk '{print $1}')
    rm $1/file$i
    c=$(diff -u <(echo "$a") <(echo "$b"))
    if [ -s c ] ; then
        echo "$c"
        echo "Hashes do not match!"
        exit
    fi
done
rm -r $1
echo "Your hashes are identical"

