#!/bin/bash
max=1024    # number of megabytes

mkdir generated
for ((i=1; i<=2; i++))
do
    echo Creating file$i
    dd bs=1M count=$(($RANDOM%max + 1)) if=/dev/urandom of=file$i
    A=$(md5sum file$i | awk '{print $1}')
    mv file$i /home/felix/generated
    B=$(md5sum /home/felix/generated/file$i | awk '{print $1}')
    diff -u <(echo "$A") <(echo "$B") > diff$i.txt
    if [ ! -s diff$i.txt ] ; then
        rm diff$i.txt
    fi
done
    rm -r generated/
    ls diff*
    echo "That is the list of corrupted files"
