#!/bin/bash
max=1024    # number of megabytes

mkdir generated
for ((i=1; i<=2; i++))
do
    echo Creating file$i
    dd bs=1M count=$(($RANDOM%max + 1)) if=/dev/urandom of=file$i
    a=$(md5sum file$i | awk '{print $1}')
    mv file$i /home/felix/generated
    b=$(md5sum /home/felix/generated/file$i | awk '{print $1}')
    rm /home/felix/generated/file$i
    c=$(diff -u <(echo "$a") <(echo "$b"))
    if [ -s c ] ; then
        echo "$c"
        echo "Hashes do not match!"
        exit
    fi
done
echo "Your hashes are identical"
